"""Render a bounded Draft PR body from AutoCI structured reports."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _load(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"expected JSON object in {path}")
    return value


def render_pr_body(report: dict, validation: dict, *, run_url: str) -> str:
    initial = report.get("initial") or {}
    final = report.get("final") or {}
    diff = report.get("diff") or {}
    usage = report.get("usage") or {}
    cost = report.get("cost") or {}
    timing = report.get("timing") or {}
    policy = report.get("workspace_policy") or {}
    files = validation.get("changed_files") or []
    file_lines = "\n".join(f"- `{path}`" for path in files[:100]) or "- None"
    return f"""## AutoCI Repair

This Draft PR was generated by Mini Claude AutoCI and requires human review.

### Result

| Metric | Value |
|---|---:|
| Initial exit code | {initial.get('exit_code', '-')} |
| Final exit code | {final.get('exit_code', '-')} |
| Repair attempts | {len(report.get('attempts') or [])} |
| Changed files | {diff.get('changed_file_count', 0)} |
| Diff | +{diff.get('insertions', 0)} / -{diff.get('deletions', 0)} |
| Input Tokens | {usage.get('input_tokens', 0)} |
| Output Tokens | {usage.get('output_tokens', 0)} |
| Estimated cost | ${float(cost.get('estimated_usd', 0.0)):.6f} |
| Total duration | {float(timing.get('total_duration_seconds', 0.0)):.2f}s |
| Repair Skill | `{report.get('skill_name') or 'none'}` |
| Patch SHA256 | `{validation.get('patch_sha256') or 'unknown'}` |

### Changed Files

{file_lines}

### Safety Gates

- Patch reapplied to the exact base commit: **passed**
- WorkspacePolicy write scope: **passed**
- Protected path and file-type checks: **passed**
- Independent test verification: **passed**
- Writable roots: `{', '.join(policy.get('writable_paths') or []) or 'not recorded'}`

### Evidence

[GitHub Actions run and downloadable artifacts]({run_url})

> Estimated cost is calculated from Mini Claude's static pricing table. Review the code and provider invoice before merging.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Render an AutoCI Draft PR body")
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--validation", type=Path, required=True)
    parser.add_argument("--run-url", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    body = render_pr_body(_load(args.report), _load(args.validation), run_url=args.run_url)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body, encoding="utf-8")


if __name__ == "__main__":
    main()
